version: '3.4'

services:
  ra_pha:
    image: ra_pha_dev
    build:
      target: dev
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["nodemon", "--inspect=0.0.0.0:9229", "app.js"]
    env_file: .env.dev